package com.datastructures.efdress;

public enum ClasCalzado {
    TENIS,MODA,TENISDEPORTIVOS,ZAPATOS,CASUALES,BOTAS,SANDALIAS,MOCASINES,GUAYOS,FORMALES,
    BOTINES,ALPARGATAS,ZAPATILLAS,PANTUFLAS,ESCOLAR,OUTDOOR,ZUECOS,TACONES,BALLERINASBALETAS,
    BOTASLLUVIA,BOTASAGUA,HAWAIANAS;



    }
