package com.datastructures.efdress;

public enum Fit{
    RECTO,SKINNY,JOGGER,PALAZZO,CULOTTE,LEGGINS,FLARE,WIDELEG,BASICO,CAPRI,CARGO,RELAX,MOMFIT,
    WIDE,MOM,REGULAR,PAPERBAG,BAGGY,SLOUCHY,SPORT,SLIM,CLASSICFIT,SLIMFIT,CARROT,OVERSIZE,SUPERSKINNY,BOYFRIEND;

}
