package com.datastructures.efdress;

public enum FitHombre {

    JOGGER,SLIM,RECTO,SKINNY,REGULAR,BASICO,SPORT,CLASSICFIT,SLIMFIT,CARROT,RELAX,
    CARGO,OVERSIZE,CAPRI,SUPERSKINNY,BOYFRIEND,LEGGINS;
}
